version: '3.8'
services:
  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      # Mounts the local nginx.conf into the container
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - fvn-network


  postgres:
    image: postgres:15-alpine
    container_name: fvn-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fogvision_db
    ports:
      - "5432:5432"
    networks:
      - fvn-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: fvn-redis
    ports:
      - "6379:6379"
    networks:
      - fvn-network

  kafka:
    image: apache/kafka:3.7.0
    container_name: fvn-kafka
    ports:
      - "9092:9092"
    networks:
      - fvn-network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fvn-kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@fvn-kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  journey-service:
    build: .
    container_name: fvn-journey-service
    ports:
      - "8089:8080"
    networks:
      - fvn-network
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://fvn-postgres:5432/fogvision_db
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=password
      - SPRING_DATA_REDIS_HOST=fvn-redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=fvn-kafka:9092
      - SPRING_KAFKA_CONSUMER_GROUP_ID=fvn-group
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_URL=jdbc:postgresql://fvn-postgres:5432/fogvision_db
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=password
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true

  pg-adminer:
    image: adminer:latest
    container_name: fvn-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - fvn-network
    depends_on:
      - postgres

  redis-ui:
    image: rediscommander/redis-commander:latest
    container_name: fvn-redis-ui
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:fvn-redis:6379 # Fixed host name
    ports:
      - "8082:8081"
    networks:
      - fvn-network
    depends_on:
      - redis

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: fvn-kafka-ui
    restart: unless-stopped
    ports:
      - "8083:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=fvn-kafka:9092 # Fixed host name
    networks:
      - fvn-network
    depends_on:
      - kafka

volumes:
  pgdata:

networks:
  fvn-network:
    external: true