### Start a new Journey
POST http://localhost:8089/api/v1/journeys/start
Content-Type: application/json

{
  "vehicleType": "Truck",
  "destination": "Bangalore"
}

###

### End a Journey (Replace the UUID)
POST http://localhost:8089/api/v1/journeys/77ce7f90-307d-4d03-b78c-054ae36611f6/end