### Start a new Journey
POST http://localhost:8089/api/v1/journeys/start
Content-Type: application/json

{
  "vehicleType": "Truck",
  "destination": "Bangalore"
}

###

### End a Journey (Replace the UUID)
POST http://localhost:8089/api/v1/journeys/86349b02-b22c-4bdc-aa2b-74f7a3c47e77/end